package net.necookie.disastersim.academy;

import net.minecraft.server.level.ServerPlayer;
import net.necookie.disastersim.world.TelemetryCsvWriter;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Thin Academy-specific adapter over {@link TelemetryCsvWriter}'s generic event-row writer. Every
 * other subsystem in this mod (fire, quake, alarm presses, extinguisher use) persists its events to
 * the same CSV/Turso pipeline; the Academy — the actual pretest/onboarding instrument — previously
 * recorded nothing durable at all, only the in-memory {@link AcademyProgress} blob that Capt.
 * Morfe's evaluation reads once and never round-trips anywhere else.
 *
 * <p>The Academy has no {@code SimulationSession} (it isn't a live disaster simulation), so this
 * owns its own lightweight per-attempt session id instead of reusing {@code SimulationManager}'s
 * session registry. {@code scenario_type} is always {@code "ACADEMY"}; the existing
 * {@code interaction_target} column carries a free-form detail string per event (hazard name, tool
 * used, or a {@code score=NN;weak=...} summary for the final outcome row) rather than widening the
 * CSV schema for a handful of Academy-only fields.
 */
public final class AcademyTelemetry {

    private static final String SCENARIO_TYPE = "ACADEMY";

    /** One id per Academy attempt; regenerated by {@link #startAttempt} so a Morfe-fail retry gets a fresh id. */
    private static final Map<UUID, String> sessionIds = new ConcurrentHashMap<>();

    private AcademyTelemetry() {}

    /** Call the moment a player's Academy run actually begins (Cruz {@code NOT_STARTED -> BRIEFING}). */
    public static void startAttempt(ServerPlayer player) {
        sessionIds.put(player.getUUID(), UUID.randomUUID().toString());
        record(player, "academy_start", null);
    }

    /** Generic per-event row — same shape {@code fire_alarm_activate}/{@code assembly_area_reached} already use. */
    public static void record(ServerPlayer player, String eventType, String detail) {
        String sessionId = sessionIds.computeIfAbsent(player.getUUID(), id -> UUID.randomUUID().toString());
        TelemetryCsvWriter.writeRow(
                sessionId,
                player.getUUID().toString(),
                SCENARIO_TYPE,
                player.level().getGameTime(),
                eventType,
                player.getX(), player.getY(), player.getZ(),
                0.0,
                detail,
                null
        );
    }
}
